spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: sails@123
  liquibase:
    enabled: false
    default-schema: ${db.schema}
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${db.schema}
  cloud:
    gcp:
      pubsub:
        enabled: true
      project-id: ib_pubsub_sub_npe
      config:
        enabled: true
      credentials:
        location: file:C:\Users\SAILS-DM93\Downloads\interview-builder-dev-29bcb0700b7b.json

db:
  schema: sails

app:
  name: Interview Builder

pubsub:
  topic: projects/interview-builder-dev/topics/ib_pubsub_topic_npe
  subscription: projects/interview-builder-dev/subscriptions/ib_pubsub_sub_npe
