spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: sails@123
  liquibase:
    enabled: false
    default-schema: ${db.schema}
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${db.schema}
  cloud:
    gcp:
      pubsub:
        enabled: true
      project-id: interviewbuilder
      config:
        enabled: true
      credentials:
        location: file:C:\Users\SAILS-DM93\Downloads\interviewbuilder-9e90ab5dba36.json

db:
  schema: sails

app:
  name: Interview Builder

pubsub:
  topic: projects/interviewbuilder/topics/interview-builder-dev
  subscription: projects/interviewbuilder/subscriptions/interview-builder-dev-sub
